application: writingsmell
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /.*
  script: app.handler

libraries:
- name: jinja2
  version: 2.6

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^README$
- ^license.md$
- ^rule_template.json$
- ^wsd_test.py$
- ^examples
- ^[^\\/]+\.html$
